### ISSUE TITLE
search button is showing instead of filter"

### ISSUE THREAD

**Issue by akshay94659** [abinbabuabu/breview#13]
Instead of filter button, we are getting search button, can you solve this issue @rajat27jha 

![image](https://user-images.githubusercontent.com/40669283/146323726-303dc3e9-b9fb-4e62-9cb5-83567c117a8f.png)

**Comment by akshay94659** [comment]
> Instead of filter button, we are getting search button, can you solve this issue @rajat27jha

**Comment by rajat27jha** [comment]
Assigned myself, will raise a PR to fix this

**Comment by rajat27jha** [comment]
Fixed in this PR: https://github.com/abinbabuabu/breview/pull/5. Hence closing.
