### ISSUE TITLE
Look and feel of friend lit page

### ISSUE THREAD

**Issue by ak672676** [abinbabuabu/breview#21]
The background color of friendlist page is not same as the main page, please make it consistent
![image](https://user-images.githubusercontent.com/46594792/146345222-180e4dc2-1fd4-4ada-a7f8-e1b19bb6f941.png)
![image](https://user-images.githubusercontent.com/46594792/146345283-91649947-5f47-4e9b-978c-c3df7707c95e.png)

**Comment by rajat27jha** [comment]
Done
